# Generated by Django 5.0.7 on 2024-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=128)),
                ('movie_description', models.TextField()),
                ('movie_image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('amenities', models.ManyToManyField(to='events.amenities')),
            ],
        ),
    ]
