# Generated by Django 5.0.7 on 2024-08-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='title',
            field=models.CharField(default='Question', max_length=100),
        ),
    ]
